apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp 
    spec:
      containers:
      - name: nodeserver
        image: sayeda21/myapp:latest
        ports:
        - containerPort: 3000
